sonar.projectKey = FRIDA_PET_SHOP
sonar.projectName = FRIDA PETSHOP
sonar.projectVersion = 1.0

sonar.sources=src
# sonar.test=test
sonar.sourceEncoding=UTF-8
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.token =sqa_3b0b917f24c29c8110ceda7f3a36139cb33e0f86

sonar.exclusions=node_modules/**,coverage/**,dist/**
# sonar.test.inclusions=test/**/*.test.js

