name: Frida Pet Shop CI/CD

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  quality-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar ESLint
        run: npm run lint

      - name: Gerar Build
        run: npm run build